class Cobranza {
  String alcCbi;
  String alfCbi;
  double alpCbi;
  double alvCbi;
  String cbiRef;
  String cedRuc;
  String cg1Cbi;
  String cg2Cbi;
  String cl1Cbi;
  String clcCbi;
  String codEmp;
  String codRef;
  String cr1Cbi;
  String fcaCbi;
  String gg1Cbi;
  String gg2Cbi;
  String gl1Cbi;
  String gr1Cbi;
  String ig1Cbi;
  String ig2Cbi;
  String il1Cbi;
  String ivaCbi;
  String lc1Ref;
  String lc2Ref;
  String lc3Ref;
  String ng1Cbi;
  String ng2Cbi;
  String nl1Cbi;
  String nomRef;
  String retCbi;
  String tg1Cbi;
  String tg2Cbi;
  String tl1Cbi;
  String tr1Cbi;

  Cobranza(
      {required this.alcCbi,
      required this.alfCbi,
      required this.alpCbi,
      required this.alvCbi,
      required this.cbiRef,
      required this.cedRuc,
      required this.cg1Cbi,
      required this.cg2Cbi,
      required this.cl1Cbi,
      required this.clcCbi,
      required this.codEmp,
      required this.codRef,
      required this.cr1Cbi,
      required this.fcaCbi,
      required this.gg1Cbi,
      required this.gg2Cbi,
      required this.gl1Cbi,
      required this.gr1Cbi,
      required this.ig1Cbi,
      required this.ig2Cbi,
      required this.il1Cbi,
      required this.ivaCbi,
      required this.lc1Ref,
      required this.lc2Ref,
      required this.lc3Ref,
      required this.ng1Cbi,
      required this.ng2Cbi,
      required this.nl1Cbi,
      required this.nomRef,
      required this.retCbi,
      required this.tg1Cbi,
      required this.tg2Cbi,
      required this.tl1Cbi,
      required this.tr1Cbi});

  factory Cobranza.fromJson(Map<String, dynamic> json) {
    return Cobranza(
      alcCbi: json['alc_cbi'],
      alfCbi: json['alf_cbi'],
      alpCbi: json['alp_cbi'],
      alvCbi: json['alv_cbi'],
      cbiRef: json['cbi_ref'],
      cedRuc: json['ced_ruc'],
      cg1Cbi: json['cg1_cbi'],
      cg2Cbi: json['cg2_cbi'],
      cl1Cbi: json['cl1_cbi'],
      clcCbi: json['clc_cbi'],
      codEmp: json['cod_emp'],
      codRef: json['cod_ref'],
      cr1Cbi: json['cr1_cbi'],
      fcaCbi: json['fca_cbi'],
      gg1Cbi: json['gg1_cbi'],
      gg2Cbi: json['gg2_cbi'],
      gl1Cbi: json['gl1_cbi'],
      gr1Cbi: json['gr1_cbi'],
      ig1Cbi: json['ig1_cbi'],
      ig2Cbi: json['ig2_cbi'],
      il1Cbi: json['il1_cbi'],
      ivaCbi: json['iva_cbi'],
      lc1Ref: json['lc1_ref'],
      lc2Ref: json['lc2_ref'],
      lc3Ref: json['lc3_ref'],
      ng1Cbi: json['ng1_cbi'],
      ng2Cbi: json['ng2_cbi'],
      nl1Cbi: json['nl1_cbi'],
      nomRef: json['nom_ref'],
      retCbi: json['ret_cbi'],
      tg1Cbi: json['tg1_cbi'],
      tg2Cbi: json['tg2_cbi'],
      tl1Cbi: json['tl1_cbi'],
      tr1Cbi: json['tr1_cbi'],
    );
  }
}
