import 'dart:convert';

class Guia {
  Guia({
    required this.codEmp,
    required this.codPto,
    required this.numGdr,
    required this.fecGdr,
    required this.codMov,
    required this.numMov,
    required this.codRef,
    required this.nomRef,
    required this.nomRxf,
    required this.cedRuc,
    required this.dirRef,
    required this.dirRxf,
    required this.dirRyf,
    required this.tlfRef,
    required this.nomAux,
    required this.nomEst,
    required this.infFac,
    required this.codTra,
    required this.obsTra,
    required this.notTra,
    required this.plcTra,
    required this.partida,
    required this.destino,
    required this.codCop,
    required this.nomCop,
    required this.corCop,
    required this.giaCop,
    required this.gexCop,
    required this.fecCop,
    required this.notCop,
    required this.plcCop,
    required this.psoCop,
    required this.bltCop,
    required this.valCop,
    required this.vsgCop,
    required this.uauCop,
    required this.fauCop,
    required this.stsSri,
    required this.stsGdr,
    required this.sfsGdr,
    required this.swsGdr,
    required this.mt1Gdr,
    required this.mt2Gdr,
    required this.ucrGdr,
    required this.fcrGdr,
    required this.uckGdr,
    required this.fckGdr,
  });

  String codEmp;
  String codPto;
  String numGdr;
  String fecGdr;
  String codMov;
  String numMov;
  String codRef;
  String nomRef;
  String nomRxf;
  String cedRuc;
  String dirRef;
  String dirRxf;
  String dirRyf;
  String tlfRef;
  String nomAux;
  String nomEst;
  String infFac;
  String codTra;
  String obsTra;
  String notTra;
  String plcTra;
  String partida;
  String destino;
  String codCop;
  String nomCop;
  String corCop;
  String giaCop;
  String gexCop;
  String fecCop;
  String notCop;
  String plcCop;
  String psoCop;
  String bltCop;
  String valCop;
  String vsgCop;
  String uauCop;
  String fauCop;
  String stsSri;
  String stsGdr;
  String sfsGdr;
  String swsGdr;
  String mt1Gdr;
  String mt2Gdr;
  String ucrGdr;
  String fcrGdr;
  String uckGdr;
  String fckGdr;

  factory Guia.fromJson(String str) => Guia.fromMap(json.decode(str));

  String toJson() => json.encode(toMap());

  factory Guia.fromMap(Map<String, dynamic> json) => Guia(
        codEmp: json["cod_emp"],
        codPto: json["cod_pto"],
        numGdr: json["num_gdr"],
        fecGdr: json["fec_gdr"],
        codMov: json["cod_mov"],
        numMov: json["num_mov"],
        codRef: json["cod_ref"],
        nomRef: json["nom_ref"],
        nomRxf: json["nom_rxf"],
        cedRuc: json["ced_ruc"],
        dirRef: json["dir_ref"],
        dirRxf: json["dir_rxf"],
        dirRyf: json["dir_ryf"],
        tlfRef: json["tlf_ref"],
        nomAux: json["nom_aux"],
        nomEst: json["nom_est"],
        infFac: json["inf_fac"],
        codTra: json["cod_tra"],
        obsTra: json["obs_tra"],
        notTra: json["not_tra"],
        plcTra: json["plc_tra"],
        partida: json["partida"],
        destino: json["destino"],
        codCop: json["cod_cop"],
        nomCop: json["nom_cop"],
        corCop: json["cor_cop"],
        giaCop: json["gia_cop"],
        gexCop: json["gex_Cop"],
        fecCop: json["fec_cop"],
        notCop: json["not_cop"],
        plcCop: json["plc_cop"],
        psoCop: json["pso_cop"],
        bltCop: json["blt_cop"],
        valCop: json["val_cop"],
        vsgCop: json["vsg_cop"],
        uauCop: json["uau_cop"],
        fauCop: json["fau_cop"],
        stsSri: json["sts_sri"],
        stsGdr: json["sts_gdr"],
        sfsGdr: json["sfs_gdr"],
        swsGdr: json["sws_gdr"],
        mt1Gdr: json["mt1_gdr"],
        mt2Gdr: json["mt2_gdr"],
        ucrGdr: json["ucr_gdr"],
        fcrGdr: json["fcr_gdr"],
        uckGdr: json["uck_gdr"],
        fckGdr: json["fck_gdr"],
      );

  Map<String, dynamic> toMap() => {
        "cod_emp": codEmp,
        "cod_pto": codPto,
        "num_gdr": numGdr,
        "fec_gdr": fecGdr,
        "cod_mov": codMov,
        "num_mov": numMov,
        "cod_ref": codRef,
        "nom_ref": nomRef,
        "nom_rxf": nomRxf,
        "ced_ruc": cedRuc,
        "dir_ref": dirRef,
        "dir_rxf": dirRxf,
        "dir_ryf": dirRyf,
        "tlf_ref": tlfRef,
        "nom_aux": nomAux,
        "nom_est": nomEst,
        "inf_fac": infFac,
        "cod_tra": codTra,
        "obs_tra": obsTra,
        "not_tra": notTra,
        "plc_tra": plcTra,
        "partida": partida,
        "destino": destino,
        "cod_cop": codCop,
        "nom_cop": nomCop,
        "cor_cop": corCop,
        "gia_cop": giaCop,
        "gex_Cop": gexCop,
        "fec_cop": fecCop,
        "not_cop": notCop,
        "plc_cop": plcCop,
        "pso_cop": psoCop,
        "blt_cop": bltCop,
        "val_cop": valCop,
        "vsg_cop": vsgCop,
        "uau_cop": uauCop,
        "fau_cop": fauCop,
        "sts_sri": stsSri,
        "sts_gdr": stsGdr,
        "sfs_gdr": sfsGdr,
        "sws_gdr": swsGdr,
        "mt1_gdr": mt1Gdr,
        "mt2_gdr": mt2Gdr,
        "ucr_gdr": ucrGdr,
        "fcr_gdr": fcrGdr,
        "uck_gdr": uckGdr,
        "fck_gdr": fckGdr,
      };
}
